import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import ReduxProvider from "./components/reduxprovider";
import {
  ClerkProvider,

} from '@clerk/nextjs'
import './globals.css'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return ( <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-bold text-center  text-2xl bg-blend-darken text-black `}
>
        <ReduxProvider>
      
      <Navbar/> 

        {children}
        <Footer/>
        </ReduxProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
